### ISSUE TITLE
Change color of .button-caption-sub in dark mode

### ISSUE THREAD

**Issue by shahednasser** [shahednasser/sbuttons#114]
Change color of `.button-caption-sub` to `#afafaf` in dark mode. You can refer to `assets/css/index.html` to figure out how to style elements in dark mode.

**Comment by nileshanand16** [comment]
can I take this issue?

**Comment by shahednasser** [comment]
Yes of course!

**Comment by nileshanand16** [comment]
}

.button-caption-sub {
  color: #afafaf;
  font-family: monospace;
  cursor: pointer;
}

**Comment by shahednasser** [comment]
You need to fork the repository, make changes to the code then create a pull request. Read more about it in the [contributing guidelines](https://github.com/shahednasser/sbuttons/blob/master/CONTRIBUTING.md)

**Comment by nileshanand16** [comment]
DONE

**Comment by shahednasser** [comment]
Hi @nileshanand16 you have pushed a commit to your repository that you forked from this. You need to create a pull request to merge your code. Please check the [contribution guidelines](https://github.com/shahednasser/sbuttons/blob/master/CONTRIBUTING.md) for more details

**Comment by HADES-01** [comment]
Can I work this issue ????

**Comment by shahednasser** [comment]
Yes @HADES-01  go ahead!
