### ISSUE TITLE
Change box shadow for sidebar on small devices in dark mode

### ISSUE THREAD

**Issue by shahednasser** [shahednasser/sbuttons#120]
When dark mode is enabled, the box shadow for the sidebar looks too bright. Change it to a darker color, but not too dark. Something that doesn't look out of place.

**Comment by esakki-selvaraj** [comment]
can I work on this?

**Comment by shahednasser** [comment]
Yes you can

**Comment by esakki-selvaraj** [comment]
![sButtons - Simple and Creative Buttons - Google Chrome 16-09-2020 7 56 28 AM](https://user-images.githubusercontent.com/66409185/93285294-2d288d00-f7f2-11ea-8267-edebf65dec7b.png)
is this color good??
