### ISSUE TITLE
Remove extra padding/margin for .close-sidebar

### ISSUE THREAD

**Issue by shahednasser** [shahednasser/sbuttons#121]
On small devices, remove the extra padding/margin for `.close-sidebar` on its right. Just leave a small padding or margin (maybe 5 or 10px)

**Comment by esakki-selvaraj** [comment]
can I work on it??

**Comment by shahednasser** [comment]
@esakki-selvaraj yes!

**Comment by esakki-selvaraj** [comment]
.close sidebar already has a padding of 6px only and margin 0px

**Comment by shahednasser** [comment]
Then it could be a positioning problem (left or right) or maybe the padding is on its container (the sidebar). Please inspect as you find the solution

**Comment by esakki-selvaraj** [comment]
what is the desired final result?

**Comment by shahednasser** [comment]
On small devices, the close icon looks too far away from the edge of the sidebar on the right. I want it closer to the edge

**Comment by esakki-selvaraj** [comment]
![sButtons - Simple and Creative Buttons - Google Chrome 15-09-2020 9 07 07 PM](https://user-images.githubusercontent.com/66409185/93232526-a3e46c80-f797-11ea-9d04-ad975fed1b38.png)
is this ok?

**Comment by shahednasser** [comment]
that's good! if you can also reduce the distance from the top that would be perfect

**Comment by esakki-selvaraj** [comment]
![sButtons - Simple and Creative Buttons - Google Chrome 15-09-2020 9 34 08 PM](https://user-images.githubusercontent.com/66409185/93235580-65e94780-f79b-11ea-8a13-0dab14a4282b.png)
How is this??

**Comment by shahednasser** [comment]
Good. Please open a pull request with your work.

**Comment by esakki-selvaraj** [comment]
Done!!!
