### ISSUE TITLE
Add download and documentation buttons in header

### ISSUE THREAD

**Issue by shahednasser** [shahednasser/sbuttons#133]
Add a download & documentation buttons in the header below the logo and text that says "Download" & "Documentation". The buttons' color is preferably white. Try to use one of the animation buttons we have, but please refrain from using a bootstrap button. For the download link, use one of the animation buttons, but as for the documentation just use outline button. Currently, we don't have a white color for the buttons, so you can just use any button color and override it in the `assets/css/index.css` for now.

If you have a good idea for the design of a button you can make a new one too. It would be nice if you can add it into the list of buttons but it's not required.

The link of the download should lead to the same download link as the one in the navbar. The link for the documentation should lead to the README.

Don't use the font we're using for the buttons, use the font we're using for the text in the header

**Comment by kanavpruthi** [comment]
I would like to work on this issue !

**Comment by shahednasser** [comment]
sure go ahead!

**Comment by yash2189** [comment]
I would like to work on this please.

**Comment by shahednasser** [comment]
@yash2189 someone is already assigned to this one. Please find other unassigned issues.

**Comment by shahednasser** [comment]
Hi @kanavpruthi are you having any trouble with this? Do you need any assistance?

**Comment by nicholedwight** [comment]
I'd like to work on this one if it's still open!
