### ISSUE TITLE
Make "display: inline-block;" for a.sbtn

### ISSUE THREAD

**Issue by shahednasser** [shahednasser/sbuttons#134]
Currently add sbuttons designs are aimed towards `<button>` elements. To add support to links as well, we need to add `display: inline-block;` for `<a>` elements that have the class `.sbtn`. Changes should be made in `src/components/_basic.less` because it should be applied to all button types

**Comment by adityasinghbaghel** [comment]
Hey!  I want  to  contribute and Fix the issue . . .
