### ISSUE TITLE
Add a link to submit new button ideas

### ISSUE THREAD

**Issue by shahednasser** [shahednasser/sbuttons#135]
In the "How to Use" section on the website, add text at the end of it that should say something like "Do you have amazing ideas for new buttons? Submit them here." where "here" is a link that would take the person to issue #96

**Comment by markkulube** [comment]
Hi, I will do it.

**Comment by shahednasser** [comment]
Great go ahead!

**Comment by markkulube** [comment]
@shahednasser remember to assign me :)

**Comment by kanavpruthi** [comment]
Is this issue still open?

**Comment by shahednasser** [comment]
hi @kanavpruthi someone is assigned to this issue. Please look at other issues that doesn't have people assigned to them.

**Comment by markkulube** [comment]
@shahednasser PR raised. Let me know if there are any issues. Thanks!
