### ISSUE TITLE
Add white button color

### ISSUE THREAD

**Issue by shahednasser** [shahednasser/sbuttons#139]
Add to the available colors a white button. I think it would be best if the button has a border, to show it properly in light mode. Or maybe a box-shadow, it's up to you.

When you add the color in variables in `src/sbuttons.less` and the style rules in `src/components/_basic.less` Make sure to add the new color in `assets/js/buttons-examples.js` to show it on the website.

Please follow the same convention as previous colors

**Comment by hbach24** [comment]
Hi is this open to first-timers? I am new to open source and was wondering if I can try contributing to this. I am willing to learn how to code this.

**Comment by hbach24** [comment]
Hi is this open to first-timers? I am new to open source and was wondering if I can try contributing to this. I am willing to learn how to code this.

**Comment by shahednasser** [comment]
Hi @hbach24 someone is already working on this. But please find any other unassigned issue that you feel like you can work on and we'd appreciate your help!

You can also look at the "Always Open" label it has issues that anyone and everyone can work on at any time. Or you can add any button ideas you have in the button ideas file for someone else to implement.

Please check out our contribution guide for more help. I'll also be happy to assist you.

**Comment by hbach24** [comment]
Okay, thank you!
