### ISSUE TITLE
Add more explanation in the "How to Use" section

### ISSUE THREAD

**Issue by shahednasser** [shahednasser/sbuttons#149]
The "How to Use" section only talks about how we can include or download the `sbuttons.min.css` file. We need to add explanation on **How to apply styles to buttons**:  

1. Add some text that explains how we should use the classes shown below button examples to any `<button>` and `<a>` tags .
2. Include 2 code blocks, one for a `<button>` element and one for an `<a>` element. Those elements should have classes of one of the examples from the website. You can use any example, it does not matter.

**This should be added to both the README and the website in "How to Use" section.**

**Comment by salonigoyal2309** [comment]
hey , i would love to take this issue :)

**Comment by yash2189** [comment]
Can I work on this?

**Comment by shahednasser** [comment]
@salonigoyal2309 go ahead!

**Comment by shahednasser** [comment]
@yash2189 please find other issues on this repo! Also, make sure the issue is not assigned to anyone.

**Comment by salonigoyal2309** [comment]
@shahednasser  I was thinking what if we change current 'USAGE' heading to 'How to Download' and we can give this issue heading as 'USAGE' ?
