### ISSUE TITLE
Close icon in the sidebar not showing on small devices when the list of items in the sidebar is long

### ISSUE THREAD

**Issue by shahednasser** [shahednasser/sbuttons#150]
This issue can be reproduced by scrolling to "Animated Buttons" section, as it is the section that makes the sidebar menu long. The issue isn't apparent on laptops even if you make the screen small. Only upon testing it on a mobile phone you can notice it.  

The problem seems to be because of adding `overflow-y: auto` to sidebar on small devices, and the links in the sidebar are siblings to `.close-sidebar`. One way to solve this could be by putting the sidebar menu links inside another container div and adding the `overflow-y: auto;` rule on it instead. 

Please note that the scrollbar on sidebar is also customized, so be sure to also move the customized scrollbar rules to the new container div instead.

**Comment by shahednasser** [comment]
@isonnymichael can you work on this issue? I think you'll know how to do it more than anyone since you know the code regarding this better

**Comment by isonnymichael** [comment]
@shahednasser okay, i will work on this issue tonight.

**Comment by isonnymichael** [comment]
@shahednasser accidentally forgot make new branch on my local, I've made changes and push to master, but I cant make pull request.. is there any changes ?

**Comment by shahednasser** [comment]
Did you make sure to pull from the master before making your changes? I think you need to sync your repository to this one

**Comment by isonnymichael** [comment]
git fetch upstream
git merge master
and nothing happend, already up to date.
