### ISSUE TITLE
Fix Black Fill (all types) and Outline buttons

### ISSUE THREAD

**Issue by reveurguy** [shahednasser/sbuttons#156]
**Describe the bug**
On the website, in the fill section, the black btns are just transparent before and after hovering in normal mode. In dark mode, the button is different than the other buttons and also the effect is still not applicable. 
Also, this error is in the outline section.
**Expected behavior of what should have happened (if applicable)**
The button before should be with a black outline and on hover, should be filled in with black color.
**Screenshots (if applicable)**
![Screenshot (160)](https://user-images.githubusercontent.com/59417546/93748852-8a6b7680-fc16-11ea-8180-4479a8ef1f08.png)
![Screenshot (158)](https://user-images.githubusercontent.com/59417546/93748858-8c353a00-fc16-11ea-9567-e4cf43370598.png)
![Screenshot (164)](https://user-images.githubusercontent.com/59417546/93749843-3c577280-fc18-11ea-8411-735ae3b77b7a.png)

**Additional notes**

**Comment by shahednasser** [comment]
This seems to be a cache issue. Please clear the cache and try again. 

However, we still need a consistent and easy way of making sure the changes on the website can always be seen without asking everyone to clear the cache. Usually this is done by adding version to css file when including it in `<head>` (for example: `sbuttons.min.css?v=728283`) but changing it manually is not such a great idea.

I'll label this as an enhancement issue. It's not something urgent but we should find a good solution for it.

Thank you for reporting this @reveurguy !

**Comment by shahednasser** [comment]
At first I thought this was a cache issue but now that you're mentioning it, it's true there's a problem with black buttons for fill color types.

If you would like to work on this, please let me know so that I can assign you @reveurguy

**Comment by reveurguy** [comment]
also for outline types and in both normal and dark modes.

**Comment by shahednasser** [comment]
@all-contributors please add @reveurguy for bug

**Comment by shahednasser** [comment]
> also for outline types and in both normal and dark modes.

That is true. I have adjusted the title accordingly to make it clearer. This issue isn't in the website, it's in the buttons themselves.

**Comment by reveurguy** [comment]
i would like to work on it but i don't know LESS

**Comment by shahednasser** [comment]
The bug fix is actually easy, you just need to refer to how previous colors are implemented for fill color and outline and add the same thing for black color.

**Comment by shahednasser** [comment]
I have fixed this issue as it has a very high priority. Thank you @reveurguy for your help reporting it.

**Comment by reveurguy** [comment]
i wanted to work on this and make the pr count for hacktoberfest.

**Comment by shahednasser** [comment]
@reveurguy hacktoberfest hasn't started yet. Pull Requests you make now will not count.
