### ISSUE TITLE
Download Button on website

### ISSUE THREAD

**Issue by reveurguy** [shahednasser/sbuttons#158]
**Describe the bug**
The download button on website opens a page with all the code. Instead it should download a file with all the code.
**Expected behavior of what should have happened (if applicable)**

**Screenshots (if applicable)**

**Additional notes**

**Comment by shahednasser** [comment]
Hi @reveurguy thank you for submitting this. I'm actually aware of that but as of now it's fine. I'll add it to enhancements though as it is something that's worth working on.

**Comment by reveurguy** [comment]
also i want to suggest to use a lighter color for dark mode, like grey or black with some opacity or a lighter black color, so that the black buttons are clearly visible.

**Comment by shahednasser** [comment]
You can submit a PR with what you mean and we'll see if it's better
