### ISSUE TITLE
Display code in how to use section using Prism.js

### ISSUE THREAD

**Issue by shahednasser** [shahednasser/sbuttons#16]
Currently, the code in "How to use section" is displayed as text like other text in the page.

Display it as a block of code by using [Prism.js](https://prismjs.com/). Please make it as simple as possible. Use CDN and the designated classes for HTML code blocks.

**Comment by isonnymichael** [comment]
Hi can I work on this ?

**Comment by shahednasser** [comment]
Yes, go ahead!

**Comment by shahednasser** [comment]
Closed by #36
