### ISSUE TITLE
Replace single quotations with double quotations in code block in website

### ISSUE THREAD

**Issue by shahednasser** [shahednasser/sbuttons#165]
On the last two code blocks in the "How to Use" section on the website, replace the single quotations with double quotations. For example, change `<a href='#'` to `<a href="#"`. This issue causes a bug in copying the code.

**Comment by AgyeyaMishra** [comment]
Hello. Hope you are doing fine. :)
I just happened to come across this issue. Can I work on it?

**Comment by shahednasser** [comment]
Hi @AgyeyaMishra go ahead!

**Comment by RishabhDevbanshi** [comment]
Hey, can I work on this issue ?
