### ISSUE TITLE
Move Pulse Buttons to its own file

### ISSUE THREAD

**Issue by shahednasser** [shahednasser/sbuttons#168]
Pulse buttons rules are in `src/components/animated/_shine.less` we need them in a new file in `src/components/animated/_pulse.less`. Don't forget to also import it in `src/components/_animated.less`.

**Comment by JoanRosell** [comment]
Hi, I'd like to tackle this one. I'm a first-time contributor, so any feedback is very welcome ^^

The (quite short) task list would look like this:

- [ ] Locate and cut pulse buttons rules
- [ ] Paste the code into a new file called _pulse.less
- [ ] Import the file in _animated.less

**Comment by shahednasser** [comment]
Looks good! @JoanRosell I'll assign you

**Comment by JoanRosell** [comment]
Ok, I have moved the code, should I run: 
`npm run watch`
`npm run prettier`
`npm run compile`


Since I haven't modified `src/sbuttons.less` I don't know if I should recompile the CSS.

**Comment by shahednasser** [comment]
Just run `npm run compile`. We need to compile the code, but it's enough to just run compile command

**Comment by JoanRosell** [comment]
Thank you for the support @shahednasser!
