### ISSUE TITLE
Fix watch command

### ISSUE THREAD

**Issue by shahednasser** [shahednasser/sbuttons#169]
watch command only watches changes in `src/sbuttons.less`. We need it to watch changes in all `.less` files in `src` and compile sbuttons.less on change.

**Comment by chaitanya4vedi** [comment]
Can i help on this? Also can we use lite-server so that the page updates automatically?

**Comment by shahednasser** [comment]
Yes @chaitanya4vedi I'm open to any idea you find useful! We need to make the watch command more helpful. I'll assign you to this issue
