### ISSUE TITLE
Change font size of toggle-theme on small devices

### ISSUE THREAD

**Issue by shahednasser** [shahednasser/sbuttons#177]
Change font size of toggle-theme (light/dark theme icon) on small devices ( < 768px) to 1.15rem. Currently, this is applied to `.download-link` so you can add to that same rule the selector for `.toggle-theme`

**Comment by AlacritousCreature** [comment]
I would like to make it. May I?

**Comment by shahednasser** [comment]
Hi @AlacritousCreature yes you can!

**Comment by AlacritousCreature** [comment]
Thanku for assigning!
Please review it...if it is correct or not.
