### ISSUE TITLE
Move code for closing sidebar to a function

### ISSUE THREAD

**Issue by shahednasser** [shahednasser/sbuttons#187]
In `assets/js/index.js` we have repeated code that closes the sidebar. We need to put it in one function and call it each time. The code is being used for 3 or 4 events, so it should be put in a separate function and then the function should be called from these events

**Comment by JLambertazzo** [comment]
I'm familiar with the code, I can take care of this!

**Comment by shahednasser** [comment]
Great @JLambertazzo I'll assign you

**Comment by DilkiSasikala** [comment]
Hi, I would like to attempt this.
