### ISSUE TITLE
Make Logo for sButtons

### ISSUE THREAD

**Issue by shahednasser** [shahednasser/sbuttons#2]
Currently, there is no logo for sButtons. Create a logo for the project.

**Comment by chaitanya4vedi** [comment]
Can i design and add logo for sButtons?

**Comment by shahednasser** [comment]
Yes @chaitanya4vedi I would totally appreciate it!

**Comment by Rishav0907** [comment]
Can i go for it?

**Comment by shahednasser** [comment]
@Rishav0907 someone is already assigned to this unfortunately. If you would like to contribute to something else, please look for issues that are not assigned to anyone.

**Comment by shahednasser** [comment]
Hi @Rishav0907 if you still want to submit a logo idea I'd love to see it. I would like to see different options before settling for a logo.
