### ISSUE TITLE
Change Button Ideas list to table

### ISSUE THREAD

**Issue by shahednasser** [shahednasser/sbuttons#208]
Currently [Button Ideas file](https://github.com/shahednasser/sbuttons/blob/master/BUTTON_IDEAS.md) has a list of ideas added by awesome contributors, however, they are not recognized for it. I want to change the list of checkboxes and labels to a table that has four columns: Empty title (for checkboxes), "Button name", "Description", "Submitted By" which would link to the profile of the person that submitted it. Each title would have a table under it (for example, table under animated, table under icon, etc...)

If you need help finding which button was added by which, you can look at the history of the file to figure it out. Ideas added by me (the owner) don't need to be credited. Just those added by other contributors.

Also, the [contributing guidelines](https://github.com/shahednasser/sbuttons/blob/master/CONTRIBUTING.md) should be updated instructing contributors how they can add a new idea (add a new row to the table) and how to check off an idea they implemented.

**Comment by Oaparecido** [comment]
Hello, what you want is to turn README.md into a table?

**Comment by shahednasser** [comment]
@Oaparecido no it's the button ideas file linked

**Comment by Caleb335** [comment]
Hi, I'd love to work on this.

**Comment by shahednasser** [comment]
Please do @Caleb335 . I'll assign you then.

**Comment by Caleb335** [comment]
> Please do @Caleb335 . I'll assign you then.

On it.
