### ISSUE TITLE
Change font for buttons in header

### ISSUE THREAD

**Issue by shahednasser** [shahednasser/sbuttons#213]
Change the font for the "Download" and "Documentation" links in the header to "Syne"

**Comment by MarthaBarahona** [comment]
Hi, can I take this issue, and submit the PR in the first days of October for Hactoberfest?

**Comment by shahednasser** [comment]
Hi @MarthaBarahona thank you for wanting to contribute! I think it's best if you come back in October and find an issue you can do. I'm sure you'll be able to find something then!

**Comment by hbach24** [comment]
Hi! Can I take this issue?

**Comment by shahednasser** [comment]
Yes @hbach24 go ahead!

**Comment by alinasahoo** [comment]
Hey, is this issue still open?
