### ISSUE TITLE
Hide "Download" button in the navbar when at the top of the page

### ISSUE THREAD

**Issue by shahednasser** [shahednasser/sbuttons#216]
When at the top of the page and the header is visible, hide the download link in the navbar. A tip: When the navbar doesn't have the class "scrolling" the download link should be hidden. When it has the class "scrolling", the download link should be visible.

**Comment by Zuhdannur** [comment]
i can work on it , assign to me

**Comment by JithinAji** [comment]
Is this issue solved?

**Comment by shahednasser** [comment]
@JithinAji someone is already working on this. Please look at other issues you can contribute to!

**Comment by JithinAji** [comment]
@shahednasser Sure. Thank you for the update.

**Comment by pinkman7009** [comment]
this issue has been open for 5 days. can i work on this if no one is currently working on it now?

**Comment by shahednasser** [comment]
@pinkman7009  Someone is working on this please choose an unassigned issue
