### ISSUE TITLE
Add Social Login buttons under "Social Buttons" type

### ISSUE THREAD

**Issue by shahednasser** [shahednasser/sbuttons#22]
Add login buttons for different social platforms. It can be for instagram, github, linkedin, or any other social media platform.
You don't have to add all types you can add as many as you want.
Please make sure to utilize the social platform's main color when making the button. You can see current buttons on the website for examples. As for the icons in the button, you can find them on font awesome.
Add new buttons under `src/components/social/` and name it _<social_platform_name>.less and import it in `src/components/_social.less`

**Comment by isonnymichael** [comment]
Can I work on this issue ?

**Comment by shahednasser** [comment]
Yes you can add as many social buttons as you want

**Comment by isonnymichael** [comment]
Do social buttons have to be written with prefix Login With xxx ?

**Comment by shahednasser** [comment]
Yes, just like in the current buttons. Please try to follow the same format and code conventions as possible. You can check `src/components/social/_google.less` for example of how the code should be like as well.

**Comment by isonnymichael** [comment]
@shahednasser okay, noted.

**Comment by amitkrishna** [comment]
HI @shahednasser I would like to take this issue I can add for github, gitlab ,bitbucket ,and do u have ang sugesstions for some more .

**Comment by shahednasser** [comment]
Sure @amitkrishna add any buttons you find suitable!

**Comment by amitkrishna** [comment]
Hi @shahednasser  wanted an input as to how should i add button description in button.css or in button.min.css or will it be generated if i add a .less file , would appreciate if i can get inputs on that.

**Comment by shahednasser** [comment]
Hi there! I'm not sure what do you mean by "button description" but all code for buttons are added in files in the `src` directory based on their type. So, adding social buttons means you should add them in `src/components/social` and then naming them and styling them using the convention (see previous buttons for reference). Once you're done, compile it by running `npm run compile` and add the button in `assets/js/buttons-examples.js`. Please refer to the [contribution guide](https://github.com/shahednasser/sbuttons/blob/master/CONTRIBUTING.md) for detailed help on all of this.

**Comment by amitkrishna** [comment]
Thank you for that input @shahednasser

**Comment by Neeraj3508** [comment]
I would like to add some social-media buttons.

**Comment by shahednasser** [comment]
@Neeraj3508 great go ahead!

**Comment by dsnehasish74** [comment]
Can I add some Buttons????

**Comment by shahednasser** [comment]
@dsnehasish74  Yes of course! You can add any type of buttons. You can also add button ideas for others to implement. Please check the [contributing guidelines](https://github.com/shahednasser/sbuttons/blob/master/CONTRIBUTING.md) for more info

**Comment by dsnehasish74** [comment]
Ok I want to add an button Login with Apple as many popular site use this button like: coursera

**Comment by Tushar11Raj** [comment]
Hey can I add social media buttons for popular websites like pinterest, tiktok and youtube?

**Comment by shahednasser** [comment]
@Tushar11Raj I don't think anyone can use tiktok to login to a website, but as for pinterest and youtube, sure go ahead!

**Comment by abdullah2205** [comment]
hi, let me try adding a snake border button

**Comment by Amit998** [comment]
is it done??else Can i try??

**Comment by shahednasser** [comment]
Hi @Amit998 this is not done yet! You can give it a shot. Please make sure to add buttons for social media platforms that actually allow you to log in on other websites using your account on your platform.

**Comment by Amit998** [comment]
Can i Add login With Microsoft and Amazon??

**Comment by dwivedi007** [comment]
Can i take this up?

**Comment by shahednasser** [comment]
> Can i Add login With Microsoft and Amazon??

Sure!

**Comment by shahednasser** [comment]
> Can i take this up?

Yes of course you can.

**Comment by reachaadrika** [comment]
Can I take this issue?

**Comment by shahednasser** [comment]
Closing this issue as we have a lot of social media buttons now. If you would like to add a new social media button, please create a "new button idea" issue.
