### ISSUE TITLE
The neon buttons should have more color options rather than just green

### ISSUE THREAD

**Issue by HADES-01** [shahednasser/sbuttons#226]
**Describe the solution you'd like**
Add more classes to [_neon.less](https://github.com/shahednasser/sbuttons/blob/master/src/components/animated/_neon.less).
And required examples should be added to the [index.html](https://github.com/shahednasser/sbuttons/blob/master/index.html) as well.

**Additional notes**
Should at least have support for all the current color combinations.

**Currently Working On It**
Yes

**Comment by shahednasser** [comment]
I like the idea. Please work on it!
