### ISSUE TITLE
Snake Border button

### ISSUE THREAD

**Issue by hvirmani** [shahednasser/sbuttons#228]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Additional notes**

**Comment by adsingh14** [comment]
- The text has gone until on hover (as well as on active/focus). Is that looking better ?
![image](https://user-images.githubusercontent.com/35252877/94974504-69ffbe00-052c-11eb-8139-8404ebb6ede7.png)

- The border goes instantly when **hoverOut** the cursor. IMO, It should gone the way it's animated on **hoverIn**.

**Comment by shahednasser** [comment]
Thank you for reporting this bug. It was due to an overlap between buttons. It has been fixed now.
