### ISSUE TITLE
DISCUSSION: Should we move "sbuttons.min.css" outside of the repository

### ISSUE THREAD

**Issue by shahednasser** [shahednasser/sbuttons#235]
As pointed out by our contributor @chaitanya4vedi , and as we have been experiencing conflicts when contributors make pull request after the `dist/sbuttons.min.css` file has changed, maybe we should consider a better solution for this.

We need the file for people to download it, as well as use it on the website. So removing it from the repository would require an alternative solution.

Does anyone have any ideas or ways they can help with? This would help with making contributions easier, as well as maintaining the project.

Maybe we can do something using Github actions? Or maybe some other way of hosting the file? Leave your ideas below!

**Comment by isonnymichael** [comment]
How if adding gitignore for .min.css ?

**Comment by shahednasser** [comment]
@isonnymichael  If we do that we need another way of hosting .min.css and a way of deploying the new version with every change.

**Comment by isonnymichael** [comment]
So we need auto deploy for any changes without conflict ? Can you explain where you deploy that file ?

**Comment by shahednasser** [comment]
I'm currently not sure. That's why I opened this issue, to get ideas from the contributors. I'll keep researching it as well but maybe someone has a good idea and can help!

**Comment by shahednasser** [comment]
Resolved this issue using [Statically](https://statically.io/). Minification is now done automatically by them. Only sbuttons.css remains in this repository

**Comment by isonnymichael** [comment]
Wow it's good, but can I know how it's work ?

**Comment by shahednasser** [comment]
If you visit their website you can see it, it's easy, but basically, if you enter the URL of a file in a repository they give you a CDN link to it. Also, they provide minification for any file, so it's pretty convenient.

**Comment by isonnymichael** [comment]
Is it automation ? In this case, you set link ../sbuttons.css and if any changes in this sbuttons file, it will generate new minify file ? If so, where's the file .min.css located ? Thanks.

**Comment by shahednasser** [comment]
Statically automatically takes the file from your repository and serves it minified

**Comment by isonnymichael** [comment]
I see.. thanks
