### ISSUE TITLE
Like Button Animation

### ISSUE THREAD

**Issue by isonnymichael** [shahednasser/sbuttons#243]
**Describe the bug**
I don't know it's bug or you make the animation just like that ? Because I think the animation look weird, please check it out.
**Expected behavior of what should have happened (if applicable)**

**Screenshots (if applicable)**

![like-button](https://user-images.githubusercontent.com/24585708/94340611-6dc3aa00-002d-11eb-8658-1e7a005e34d2.gif)

**Additional notes**

**Comment by shahednasser** [comment]
I get your point @isonnymichael . If you wanna work on it, let me know to assign you.

**Comment by isonnymichael** [comment]
If no one work on it, assign me for tomorrow, can I ?

**Comment by shahednasser** [comment]
Sure, I'll assign you!
