### ISSUE TITLE
Change in Sidebar Nav .items Font Family !

### ISSUE THREAD

**Issue by icoderharshit** [shahednasser/sbuttons#247]
**Describe the bug**
Text in the Nav. items of sidebar looks really congested and font family also looks not so aesthetic.
**Expected behavior of what should have happened (if applicable)**
either text spacing should have been given for the nav. item's or the font family and the line-height should be increased a little.
Furthermore, the transition duration of the underline coming below the items should be improved. 
**Screenshots (if applicable)**
![bug](https://user-images.githubusercontent.com/55023091/94342251-7c11c600-002d-11eb-9c84-0ea4b43b5d9e.JPG)

**Additional notes**
I want to work over this, please let me know. So, that I can make the change for good !

**Comment by shahednasser** [comment]
I see your point. Please work on it and let me see how it should look like.

**Comment by icoderharshit** [comment]
Sure, I will be updating the same by today!

**Comment by icoderharshit** [comment]
I pulled request on this issue and did the improvement in a new branch "SIdebar-Nav.-items'-design-Fix" ! Check it out @shahednasser

**Comment by icoderharshit** [comment]
I committed the requested change @shahednasser , please see to it :).
