### ISSUE TITLE
Banner links don't go with the overall aesthetic of the website

### ISSUE THREAD

**Issue by HADES-01** [shahednasser/sbuttons#252]
**Describe the bug**
The "Download" and "Documentation" links in the banner of the website don't go with the overall aesthetic of website.
**Screenshots (if applicable)**
Should look like this
![Should look like](https://user-images.githubusercontent.com/52060608/94347255-2f8bb200-0050-11eb-86f6-3c26b1bbb64d.png)

**Comment by shahednasser** [comment]
If you can make a pull request with the change I might look into it. But can you at least make the download button a white color? We need to put focus on the download button.
