### ISSUE TITLE
Discussion: Creating an NPM package

### ISSUE THREAD

**Issue by shahednasser** [shahednasser/sbuttons#254]
Should we create an NPM package for sButtons? Please let me know if you think it's a good idea or not, and if there are any features or additions we can add if we make it an NPM package.

**Comment by ankitksh81** [comment]
Hi @shahednasser , I think it's a good idea to create an NPM package for sButtons. It will make the installation and use of sButtons easy as we won't have to include the links in different files and we can directly install it using npm withing seconds.
We can also include other features with this package in futures. Let me know if I can help in any way possible, I would love to help.

**Comment by isonnymichael** [comment]
Yes, I think it's good

**Comment by HADES-01** [comment]
Yeah @shahednasser , It is a pretty good idea. Let me know as well if I can help in any way possible.

**Comment by shahednasser** [comment]
I'm honestly not sure what is the best way to do it so I'll need to look into it. If you have any notes, suggestions or ways to help please let me know!
