### ISSUE TITLE
Add a link to CONTRIBUTORS.md in the footer

### ISSUE THREAD

**Issue by shahednasser** [shahednasser/sbuttons#266]
In the footer of the website, add a link to the CONTRIBUTORS.md. The text should be something like "Here's a list of our awesome contributors" or anything better.

**Comment by chaitanya4vedi** [comment]
@shahednasser Can i do this?

**Comment by chaitanya4vedi** [comment]
@shahednasser Also How do i proceed with implementing some ideas or improvements? like i see we use prettier in this project. So we can use precommit hooks to run prettier every time a commit is made. So do i open new pull request for each ideas or open an issue first and then proceed?

**Comment by shahednasser** [comment]
Yes you can work on this @chaitanya4vedi . As for the idea, please send an issue first to discuss and see if it should be implemented.

Regarding prettier, there's already an action that runs on push and merging pull requests to the repository.

**Comment by chaitanya4vedi** [comment]
> Yes you can work on this @chaitanya4vedi . As for the idea, please send an issue first to discuss and see if it should be implemented.
> 
> Regarding prettier, there's already an action that runs on push and merging pull requests to the repository.

I see. Ok thanks.
