### ISSUE TITLE
Add a "Scroll to top" button

### ISSUE THREAD

**Issue by shahednasser** [shahednasser/sbuttons#27]
As the website can get lengthy, we need a button on the bottom right corner that appears after scrolling a little and that can take the user back to top on click.

**Comment by Pratyush-Saxena** [comment]
@shahednasser can i work on this issue

**Comment by shahednasser** [comment]
Yes go ahead!

**Comment by Pratyush-Saxena** [comment]
@shahednasser pls check out my pr #34
