### ISSUE TITLE
The text of social buttons are not visible clearly

### ISSUE THREAD

**Issue by dsnehasish74** [shahednasser/sbuttons#273]
![Screenshot (162)_LI](https://user-images.githubusercontent.com/58779604/94372415-e2284700-011a-11eb-95c2-df41c0e4833f.jpg)
**Describe the bug**

**Expected behavior of what should have happened (if applicable)**

**Screenshots (if applicable)**

**Additional notes**

**Comment by dsnehasish74** [comment]
I think changing the font family will help here...... which font family should I add here

**Comment by Pratyush-Saxena** [comment]
@dsnehasish74 i didn't found any such problem in the page ..i guess the page might not loaded properly

**Comment by dsnehasish74** [comment]
the lower portion of g is getting cut. Is not it  ???? or it is the font style???????????

**Comment by shahednasser** [comment]
> the lower portion of g is getting cut. Is not it ???? or it is the font style???????????

This is due to the font
