### ISSUE TITLE
Cannot see items in sidebar when it overflows on the big screen

### ISSUE THREAD

**Issue by shahednasser** [shahednasser/sbuttons#285]
We have added scroll rules to the sidebar on small devices. We need to change it now to all devices instead of small devices. Please maintain the same design, just change it from only small screens to all screens.

**Comment by rishipurwar1** [comment]
I would like to contribute.

**Comment by shahednasser** [comment]
Great @rishipurwar1 I'll assign you.

**Comment by rishipurwar1** [comment]
Could you please add more details about an issue?

**Comment by shahednasser** [comment]
Currently on small devices, overflow scrolling is added to `.sidebar`. We want to make it for all devices, not just small devices (basically remove the media query). You can find the code for it in `assets/css/index.css` on like 293.

Also, the sidebar's scrollbar is customized so make sure to make that visible on all devices as well.

Please check the [contributing guidelines](https://github.com/shahednasser/sbuttons/blob/master/CONTRIBUTING.md) for more details about how to contribute. If you need any assistance, let me know.

**Comment by shahednasser** [comment]
This issue has been resolved due to its high priority. @rishipurwar1 if you would like to contribute to something else please go ahead.
