### ISSUE TITLE
Find better icon similar to the logo

### ISSUE THREAD

**Issue by shahednasser** [shahednasser/sbuttons#286]
We have finally added a logo, but I'm not fond of the icon much. If anyone can find a similar icon but more flat then please add a link under this request. (This issue does not require a pull request but you will still be added as a contributor).

If someone also has better ideas for the logo as well, please share with us!

**Comment by icoderharshit** [comment]
https://drive.google.com/file/d/1UD0Yhs097r590XIFBIZ0Z992_EyBczAB/view?usp=sharing 

Tried to make a better logo :) Check it out @shahednasser

**Comment by shahednasser** [comment]
I like that @icoderharshit but do you think it will look good in the navbar? Also, would it look good with both light and dark mode? 

If we use it we also would need a version of it where the background is white and the text is colored to use it in the header of the website (since the background of the header is blue). Let me know what you think about all of this.

**Comment by icoderharshit** [comment]
Yes, it will. Being a Graphics Designer, I can tell you that it'll suit and adjust according to the background color of the header and stuff...I shared a mockup with you, if you assign me...I'll try to give it a final look and check if that goes well on Navbar as well..and with that dark mode too.

**Comment by icoderharshit** [comment]
> We have finally added a logo, but I'm not fond of the icon much. If anyone can find a similar icon but more flat then please add a link under this request. (This issue does not require a pull request but you will still be added as a contributor).
> 
> If someone also has better ideas for the logo as well, please share with us!

and yes...I just checked my name in the list of Contributors, it is redirecting to my sourcerer profile..please update it by replacing with either github.com/icoderharshit or icoderharshit.github.io/Portfolio

**Comment by shahednasser** [comment]
> Yes, it will. Being a Graphics Designer, I can tell you that it'll suit and adjust according to the background color of the header and stuff...I shared a mockup with you, if you assign me...I'll try to give it a final look and check if that goes well on Navbar as well..and with that dark mode too.

Ok I will be assigning you. Please submit a PR so I can see how it will end up looking like.

**Comment by shahednasser** [comment]
> > We have finally added a logo, but I'm not fond of the icon much. If anyone can find a similar icon but more flat then please add a link under this request. (This issue does not require a pull request but you will still be added as a contributor).
> > If someone also has better ideas for the logo as well, please share with us!
> 
> and yes...I just checked my name in the list of Contributors, it is redirecting to my sourcerer profile..please update it by replacing with either github.com/icoderharshit or icoderharshit.github.io/Portfolio

Unfortunately this is done automatically by all-contributors but I'll look into it.

**Comment by shahednasser** [comment]
@icoderharshit When you add your logo, make sure to credit yourself in the footer instead of the current credit for the icon in the logo.

**Comment by icoderharshit** [comment]
Sure, if I needed assistance in this footer thing, I'll tell you @shahednasser

**Comment by icoderharshit** [comment]
@shahednasser , I created a PR for the same and updated the website with a new logo for Header and Navbar sections (compatible both with Light and Dark mode), Please Check it out.

**Comment by icoderharshit** [comment]
Looking towards having this PR merged :) I'll look into the favicon part tomorrow morning. Please check this out @shahednasser

**Comment by icoderharshit** [comment]
Logo Updated,  and credits given in the Footer, Readme ! Check it out @shahednasser :)

**Comment by icoderharshit** [comment]
Logo and credits mentioned in the Readme file :) Please, Check @shahednasser .

**Comment by icoderharshit** [comment]
when will this issue get close ? :-p , anyways Thank you so much if you liked the work. Looking for that favicon issue, there are developers excitedly waiting to work over that.

**Comment by shahednasser** [comment]
Hi @icoderharshit can you provide me with a good quality of the logo icon which we use for favicon?

**Comment by icoderharshit** [comment]
Yeah, here you go @shahednasser :)
![favicon](https://user-images.githubusercontent.com/55023091/94921321-b79d0c00-04d5-11eb-93ea-d8e89191fd19.png)

**Comment by shahednasser** [comment]
Thank you but I need it bigger if possible (I'm using it to create a gitub organization)

**Comment by icoderharshit** [comment]
Alright, let me just do it for you ! Give me some time :)

**Comment by icoderharshit** [comment]
Here, it is @shahednasser 
[favicon.zip](https://github.com/sButtons/sbuttons/files/5317879/favicon.zip)
Uploaded a .zip file because GitHub doesn't allow sharing .svg directly here, there's a SVG file for the favicon in the ZIP.

**Comment by shahednasser** [comment]
Thank you @icoderharshit but the svg is empty for some reason

**Comment by icoderharshit** [comment]
No, @shahednasser You may have encountered a system error, please checking it once again. It's opening and working completely fine on my desktop.

**Comment by shahednasser** [comment]
My mistake it's working well. Thank you!
