### ISSUE TITLE
Changing Hover Button behavior

### ISSUE THREAD

**Issue by shahednasser** [shahednasser/sbuttons#297]
Hover Button behavior should change as the following

1. Make button lighter on hover if the button is originally dark (For example, black button).
2. Make button darker on hover if the button is originally light (For example, yellow button)

**Comment by shahednasser** [comment]
@apoorvakadam would you like to work on it (so I can assign you) or should we leave it up for someone else?

**Comment by Balaguru4580** [comment]
Hey, I can work on it if you want. Is that alright?

**Comment by shahednasser** [comment]
Hi @Balaguru4580 I'm waiting for a response from @apoorvakadam . I'll let you know if this issue stays unassigned!

**Comment by shahednasser** [comment]
Hi @Balaguru4580 as @apoorvakadam hasn't replied, you will be assigned to this issue. Please let me know if you need any assistance.
