### ISSUE TITLE
Change google font URL to include swap

### ISSUE THREAD

**Issue by shahednasser** [shahednasser/sbuttons#3]
Modify the URL for google font in `index.html` to include the `display=swap` attribute.

The font used for the website is Oleo Script Swash Caps. You can find the correct URL [here](https://fonts.google.com/specimen/Oleo+Script+Swash+Caps?query=oleo&sidebar.open=true&selection.family=Oleo+Script+Swash+Caps:wght@400;700)

**Comment by FrancescaDev** [comment]
I would like to do this one. I am a first-timer :-)

**Comment by shahednasser** [comment]
Great! Go ahead.

**Comment by FrancescaDev** [comment]
Hello @shahednasser In the link it is including both 400 & 700 weights. Did you want only weight 700? :-)
