### ISSUE TITLE
Header links not responsive

### ISSUE THREAD

**Issue by HADES-01** [shahednasser/sbuttons#300]
**Describe the bug**
The header links overflow to bottom in mobile view.

**Expected behavior of what should have happened (if applicable)**
They should stay inside the header or come inside the side menu

**Screenshots (if applicable)**
![Header link bug](https://user-images.githubusercontent.com/52060608/94580230-4bcd6000-0297-11eb-93de-ecd818e91e64.png)

**Comment by shahednasser** [comment]
Thank you @HADES-01 for reporting this bug. Upon testing it it seems that this occurs on devices with width <= 368px so maybe it would be best to hide those links on devices with width <= 368px.

**Comment by HADES-01** [comment]
@shahednasser I can get started on it. If you'd like.

**Comment by shahednasser** [comment]
sure I'll assign you @HADES-01
