### ISSUE TITLE
Change "btn-disabled" to "disabled-btn"

### ISSUE THREAD

**Issue by shahednasser** [shahednasser/sbuttons#308]
Now we have a new button type "Disabled" but its class name does not follow the convention we are using for the website. We just need to change the class name from "btn-disabled" to "disabled-btn"

**Comment by Haniket** [comment]
can I work on it

**Comment by shahednasser** [comment]
Sure @Haniket I will assign you!

**Comment by Haniket** [comment]
@shahednasser where I have to make changes in the code base....can you please help I am new to open source

**Comment by shahednasser** [comment]
@Haniket changes first need to be made in `src/components/_basic.less` in this part of the code:
https://github.com/shahednasser/sbuttons/blob/0d0ced470193ccd3a373381b32fefed13e94ee2a/src/components/_basic.less#L51-L55

You just need to change `btn-disabled` to `disabled-btn`.

Then, you need to change the class name here as well:

https://github.com/shahednasser/sbuttons/blob/0d0ced470193ccd3a373381b32fefed13e94ee2a/assets/js/buttons-examples.js#L121-L125

And finally, there's some explanation in `index.html` you can see it in the "How to Use" section of the website. Just change the class name where necessary in it.

Please also check out the [contributing guidelines](https://github.com/shahednasser/sbuttons/blob/master/CONTRIBUTING.md) for more help on how to contribute. If you need any more assistance please let me know.

**Comment by Haniket** [comment]
@shahednasser what about changing  code in sbuttons/dist/sbuttons.css
`.btn-disabled {
  opacity: 0.55;
  cursor: not-allowed;
  pointer-events: none;
}`

this part of code because here also it must be changes..........isn't it??
plz help

**Comment by shahednasser** [comment]
No @Haniket after making the changes in the less file as indicated above you need to compile the code by running `npm run compile` which will automatically update `dist/sbuttons.css`. You shouldn't manually update `dist/sbuttons.css`.

Please read the [contributing guidelines](https://github.com/shahednasser/sbuttons/blob/master/CONTRIBUTING.md) for more help on this.

**Comment by Uttam-Singhh** [comment]
Hey, Can u Assign me any issue?

**Comment by shahednasser** [comment]
Hi @Uttam-Singhh please find an unassigned issue that you think you can work on and let me know in that issue if you can do it. There are also issues with the "Always Open" label that anyone can work on at any times so be sure to check those out as well!

**Comment by Uttam-Singhh** [comment]
Hey @shahednasser I saw the all the issues but all were assigned to someone
Can you please create a new issue an assign it to me?
I can work on anything.

**Comment by shahednasser** [comment]
@Uttam-Singhh you can watch this repository if you want and keep up with any new issue!
