### ISSUE TITLE
Improve style of `.social-btn` with class `block-btn`

### ISSUE THREAD

**Issue by shahednasser** [shahednasser/sbuttons#309]
Social Buttons that are also blocks have the icons at the very far right. It should be next to the "Login with ..." text

**Comment by chaitanya4vedi** [comment]
@shahednasser Can i do this?

**Comment by shahednasser** [comment]
Yes @chaitanya4vedi I'll assign you

**Comment by pinkman7009** [comment]
can i work on this?

**Comment by shahednasser** [comment]
@pinkman7009  Someone is already working on this. please choose an unassigned issue

**Comment by chaitanya4vedi** [comment]
> Yes @chaitanya4vedi I'll assign you

@shahednasser you can unassign me as I might take some more time to do this and somone is already interested in this

**Comment by pinkman7009** [comment]
@shahednasser so can i work on it now?

**Comment by shahednasser** [comment]
Sure @chaitanya4vedi .

Assigning @pinkman7009

**Comment by pinkman7009** [comment]
thank you. i will start working on this now.

**Comment by adsingh14** [comment]
Social buttons not vertically centered align. I can fix this.

**Comment by adsingh14** [comment]
Social buttons not centered aligned vertically . I can fix this.

**Comment by tushar2407** [comment]
Hi.! The icons are not aligned with respect to text in Y-axis. I can fix that. Can you assign me this?

**Comment by shahednasser** [comment]
@adsingh14 @tushar2407 someone is assigned to this issue. Please look for unassigned issues.
