### ISSUE TITLE
Add Block and Disabled buttons documentation from website to Readme

### ISSUE THREAD

**Issue by shahednasser** [shahednasser/sbuttons#310]
Currently the documentation in "How to Use" section on the website is ahead of the "Usage" section in the README. Update the README Usage section to match the "How to Use" section.

**Comment by lee00286** [comment]
Can I work on this issue?

**Comment by shahednasser** [comment]
Sure @lee00286 I'll assign you

**Comment by Rohit-Gupta11** [comment]
Can I also work on this issue ?

**Comment by shahednasser** [comment]
Hi @Rohit-Gupta11 I think it's unnecessary since someone is already working on it. Please find another issue to contribute to!
