### ISSUE TITLE
Disable selecting text of "Disabled Buttons"

### ISSUE THREAD

**Issue by shahednasser** [shahednasser/sbuttons#312]
Disable selecing text of "Disabled Buttons" using CSS only.

**Comment by 1880akshay** [comment]
@shahednasser can u please elaborate a bit on this issue..not getting exactly what is the issue

**Comment by shahednasser** [comment]
@1880akshay when double clicking a button of type "Disabled" you can select the text of the button. This should be disabled using CSS.

**Comment by 1880akshay** [comment]
@shahednasser okay got it! can you please assign this issue to me?

**Comment by shahednasser** [comment]
Sure @1880akshay !

**Comment by 1880akshay** [comment]
Hey, @shahednasser the minified css file (sbuttons.min.css) is not updated. I mean no styles are defined for the class  btn-disabled. What should I do? Should I only add styles to the main css file (sbuttons.css) or shall first update the minified file using the main file?

**Comment by shahednasser** [comment]
You don't need to work on the minified file @1880akshay the change should be made in the less file in `src/components/_basic.less` then after that you run compile by running `npm run compile`. the minified CSS is only updated on updating the repo. Please check more info on the [contributing guidelines](https://github.com/shahednasser/sbuttons/blob/master/CONTRIBUTING.md)

**Comment by 1880akshay** [comment]
@shahednasser Please have a look at #325
