### ISSUE TITLE
Improve design of the footer

### ISSUE THREAD

**Issue by shahednasser** [shahednasser/sbuttons#313]
The design of the footer currently looks dull. Improve it to look more visually pleasing.

I'm not assigning someone specific for this issue as I would like to see different people's implementations and ideas to this. The best looking one will be picked.

**Comment by alabo-excel** [comment]
Hi, I want to do this for hacktoberfest can you please assign it to me? Thanks in advance 😃

**Comment by shahednasser** [comment]
Hi @alabo-excel you can work on this issue but as I said in the description I'm not assigning it into anyone in particular to see different results.

**Comment by DevanshD3** [comment]
Hey so how exactly do we contribute to this project? Where can we see the current footer? I am new to this, It would be great if you could help

**Comment by shahednasser** [comment]
Hello @DevanshD3 please check out the website of this repository, that's where you'll see the footer. If you want to contribute, follow the [contributing guidelines](https://github.com/shahednasser/sbuttons/blob/master/CONTRIBUTING.md). If you need any further assistance please let me know

**Comment by DevanshD3** [comment]
Hey saw your website its super awesome! Do you just want the design or the implementation as well ?

**Comment by shahednasser** [comment]
The main target is changing the design but if you have any additional ideas that you would think will make it look better then I'd love to see it as well.

**Comment by shahednasser** [comment]
@icoderharshit if you have any input on this as well let me know

**Comment by icoderharshit** [comment]
Alright, will be seeing to it soon.

**Comment by Dhiraj3118** [comment]
I have made a pull request after slightly improving footer design. I have just changed the colors to those matching the website.
