### ISSUE TITLE
Change font size of social-btn to 1.2rem

### ISSUE THREAD

**Issue by shahednasser** [shahednasser/sbuttons#314]
Currently the font-size of `.social-btn` is 1rem. Change it to 1.2rem

**Comment by arpancodes** [comment]
hello @shahednasser I would like to take it up for hacktoberfest, can you please assign it to me? Thanks! 😄

**Comment by yuvraj23092001** [comment]
Hello I would like to contribute if you allow so .
Thanks

**Comment by shahednasser** [comment]
Hi @arpancodes you can go ahead as you were first to claim it.

@yuvraj23092001 please find other issues to contribute to!

**Comment by tahseenzahra** [comment]
hello, @shahednasser can I do this challenge is it available?

**Comment by shahednasser** [comment]
HI, @tahseenzahra this issue has been resolved. Please look at other issues you can contribute to!
