### ISSUE TITLE
Add strikethrough to finished button ideas

### ISSUE THREAD

**Issue by shahednasser** [shahednasser/sbuttons#315]
There are [button ideas](https://github.com/shahednasser/sbuttons/blob/master/BUTTON_IDEAS.md) that are checked off but don't have a strikethrough. We just need to add a strikethrough to those checked off.

**Comment by joshalling** [comment]
I'd like to take this one.

**Comment by shahednasser** [comment]
Sure @joshalling i'll assign you

**Comment by Archis19** [comment]
Can I also work on this one?

**Comment by Sevicode** [comment]
Hi @shahednasser , can I work on this one? First timer here  :)

**Comment by shahednasser** [comment]
This issue has been resolved
