### ISSUE TITLE
Replace website main color with CSS custom property

### ISSUE THREAD

**Issue by shahednasser** [shahednasser/sbuttons#35]
Currently in `assets/css/index.css` we're using `#3a91ff` for the main color. We are using this color for a couple of attributes, and we probably will be using it more.

Create the file `assets/css/variables.css` and add in it custom property `--main-color` on `:root` with the value `#3a91ff` then import this file in the beginning of `assets/css/index.css` and replace `#3a91ff` throughout the file with `var(--main-color)`

**Comment by isonnymichael** [comment]
Can I try to work on this ?

**Comment by shahednasser** [comment]
Sorry, this one is for first-timers only! You can work on anything that doesn't have the first-timers-only label and that no one is assigned to.

**Comment by isonnymichael** [comment]
@shahednasser oohh okay didn't see the label..

**Comment by NirajGohel** [comment]
Hi 
Can I try to work on this?

**Comment by shahednasser** [comment]
Hi @NirajGohel yes go ahead

**Comment by shahednasser** [comment]
Resolved by #41
