### ISSUE TITLE
Add a note about using font awesome for some buttons

### ISSUE THREAD

**Issue by shahednasser** [shahednasser/sbuttons#38]
Currently, in our Usage docs and on the "How to Use" section of the website, we don't have a note about font awesome being needed for some buttons like Icon buttons and Social media login button. 

Add a little explanation of when font awesome is needed and include a code block of adding font awesome using their cdn. It should be added to both README and "How to Use" section.

**Comment by lee00286** [comment]
Hello, may I work on editing README and How to Use section?

**Comment by shahednasser** [comment]
yes, please!

**Comment by shahednasser** [comment]
Resolved by #52
