### ISSUE TITLE
Add new get started page to website and remove the How to Use section

### ISSUE THREAD

**Issue by shahednasser** [shahednasser/sbuttons#391]
Add a new Get Started page in the website. The content of the page should be the same as the "Installation" and "Usage" sections in the Readme. The new page should follow the same design as the main page of the website.

Then change the how to use Section, and replace the "Documentation" link in the header with the link to the new page and change the text to "Get Started"

This is an urgent change so only work on this if you can finish it today.

**Comment by nicholedwight** [comment]
I'd love to work on this :)

**Comment by shahednasser** [comment]
great @nicholedwight I'll assign you

**Comment by nicholedwight** [comment]
Awesome! I'll get cracking on it, it'll be done today :D

**Comment by Dhiraj3118** [comment]
I would also like to work on it but I think this is assigned. so are there any other unassigned issues?

**Comment by nicholedwight** [comment]
Hey @shahednasser, since this new Get Started page contains all the same info in our How To Use section on the main page, do you want that deleted? In your initial message you just say to change the How To Use section.

**Comment by shahednasser** [comment]
@nicholedwight yes I meant to say delete that section. Thank you for noticing!

**Comment by nicholedwight** [comment]
Perfect!

**Comment by shahednasser** [comment]
@adsingh14 someone is already working on this.

**Comment by TanishqRana** [comment]
Are other people done so I can have my shot?

**Comment by shahednasser** [comment]
Issue has been resolved
