### ISSUE TITLE
Add "How to Use" section to the website

### ISSUE THREAD

**Issue by shahednasser** [shahednasser/sbuttons#4]
At the top of the website, add "How to Use" section that demonstrates how to download or use the CDN for the CSS, and how to put it in the head tag of the page. Should be similar to the Usage section in README.

**Comment by alannaemmrie** [comment]
Hi! I can do this.

**Comment by alannaemmrie** [comment]
Should this be added as a separate page, or would you like it to just link at the bottom or something? I notice that most of the website info is just one page, so don't want to add another page if that isn't your design plan.

**Comment by shahednasser** [comment]
Issue resolved by #14 .
