### ISSUE TITLE
Active sidebar not pointing on right content

### ISSUE THREAD

**Issue by isonnymichael** [shahednasser/sbuttons#40]
**Describe the bug**
When I click the sidebar menu, the active sidebar is not pointing on right content.
![Screenshot_1](https://user-images.githubusercontent.com/24585708/92340305-011b5680-f0e4-11ea-8d08-e6898f640c5c.png)

**Expected behavior of what should have happened (if applicable)**
The active sidebar menu must pointing on right content.
![Screenshot_2](https://user-images.githubusercontent.com/24585708/92340389-5192b400-f0e4-11ea-8633-a70dbb227e30.png)

**Screenshots (if applicable)**

**Additional notes**

**Comment by shahednasser** [comment]
Good catch.  I think this could be due to the CSS margin. Will work on a fix in the js function.

**Comment by isonnymichael** [comment]
Yes I think so, I will fix it in the js function

**Comment by shahednasser** [comment]
alright great!

**Comment by shahednasser** [comment]
Resolved by #46
