### ISSUE TITLE
Find a better favicon

### ISSUE THREAD

**Issue by shahednasser** [shahednasser/sbuttons#406]
We have a new logo now thanks to @icoderharshit and now we need a new favicon. If anyone has any ideas please submit them to pick from them!

This issue will not be assigned to anyone in particular. We're looking for ideas from everyone.

**Comment by ibhavikamalhotra** [comment]
I have an idea of making a favicon similar to the new logo will be updating you with the new favicon soon.

**Comment by psk907** [comment]
I will create a favicon.ico based on @icoderharshit 's logo and provide you with the link in this thread

**Comment by NecroTechno** [comment]
We could do something like this, based off the new logo!

![sbuttons_favicon](https://user-images.githubusercontent.com/4073413/94799738-80e2cb00-03db-11eb-9102-776dd428af6d.png)

**Comment by shahednasser** [comment]
@NecroTechno can you submit a pull request with the updated favicon so that I can compare and choose between different ideas

**Comment by NecroTechno** [comment]
> @NecroTechno can you submit a pull request with the updated favicon so that I can compare and choose between different ideas

Sure thing!

**Comment by Mancancode** [comment]
I just did 4 favicons, I will do PR for it now, check it out.

**Comment by palakyadav1807** [comment]
@shahednasser can you assign this to me?
