### ISSUE TITLE
Add Neon Social Button

### ISSUE THREAD

**Issue by Neeraj3508** [shahednasser/sbuttons#410]
Add neon glow social button with icon only and one with icon as well as text.

**Comment by shahednasser** [comment]
Hi @Neeraj3508 can you verify this can't be done by using classes `neon-btn` and the class for the social media platform (for example `facebook` together?

**Comment by Neeraj3508** [comment]
why don't we create a seperate class with name facebook-neon for example

**Comment by Neeraj3508** [comment]
right?

**Comment by shahednasser** [comment]
@Neeraj3508 if it can be done by combining classes then it's better in my opinion.

**Comment by Neeraj3508** [comment]
Ok i will check both ways and if your method is applicable.

**Comment by Kazeno21** [comment]
@shahednasser is right, you don't need to create another one. we can simply add the class name

**Comment by Neeraj3508** [comment]
ok i will do it that way

**Comment by shahednasser** [comment]
No need to do it @Neeraj3508 . Closing this issue.
