### ISSUE TITLE
Click button animation style

### ISSUE THREAD

**Issue by Pratyush-Saxena** [shahednasser/sbuttons#42]
**CHANGE IN CLICK BUTTON STYLE**
I guess Click button that u have made will look much better if it would be like
this one :
![click_button](https://user-images.githubusercontent.com/52444607/92356284-7a767180-f103-11ea-9dae-f0bbfefa3f22.gif)
rather than this one :
![click_2](https://user-images.githubusercontent.com/52444607/92356325-82361600-f103-11ea-85e2-7afdbcc1ceae.gif)

**Additional notes**

**Comment by shahednasser** [comment]
Good idea. Could you work on it?

**Comment by Pratyush-Saxena** [comment]
Yeah sure!

**Comment by shahednasser** [comment]
Resolved by #87
