### ISSUE TITLE
[BUTTON IDEA]: Icon Button

### ISSUE THREAD

**Issue by shahednasser** [shahednasser/sbuttons#423]
**1. Name of button**: Icon Button

**2. Description**: A button with icons enlargement and shrink effect on hover

**3. Button Type (Animated, Special, etc...)**: Icon

**4. Will you work on it?**: no

**submitted by**: @devSouvik

**Comment by chinmaikaveti2001** [comment]
hi!  can u please assign this issue to me...?
I want to work on this issue...

**Comment by HeinKhantZaw** [comment]
Can I work for this issue?

**Comment by shahednasser** [comment]
Hi @chinmaikaveti2001 you've been assigned to a few now. Please finish them first before assigning you to anything new.

**Comment by aayushi221** [comment]
hey, i'd like to work on this issue, I would also add some animation effect to just simple icon enlargement if it's okay.
