### ISSUE TITLE
[BUTTON IDEA]: Play Game Button

### ISSUE THREAD

**Issue by shahednasser** [shahednasser/sbuttons#428]
**1. Name of button**: Play Game Button

**2. Description**: A play game button which has a game controller shape

**3. Button Type (Animated, Special, etc...)**: Icon

**4. Will you work on it?**: no

**submitted by**: @Nicolakacha

**Comment by chinmaikaveti2001** [comment]
hi! sir can u please assign this issue to me.....?
I want to work on this issue....

**Comment by chinmaikaveti2001** [comment]
hi!  can u please assign this issue to me...?
I want  to work on this issue......

**Comment by shahednasser** [comment]
sure @chinmaikaveti2001 I'll assign you.

**Comment by zilyukina** [comment]
oh, haven't seen comments before submitting PR :(
should i close my PR?
