### ISSUE TITLE
[BUTTON IDEA]: Bring to Top Button

### ISSUE THREAD

**Issue by shahednasser** [shahednasser/sbuttons#429]
**1. Name of button**: Bring to Top Button

**2. Description**: A button with an UP arrow key to glide to the top of the page

**3. Button Type (Animated, Special, etc...)**: Icon

**4. Will you work on it?**: no

**submitted by**: @Archis19

**Comment by adsingh14** [comment]
Shall I start working on it ? Just tell me you want the instant scroll to top or smooth-scroll to top ?

**Comment by adsingh14** [comment]
Shall I start working on it ? Just tell me the scroll behavior, do you want the **instant scroll** or **smooth-scroll** to top ?

**Comment by shahednasser** [comment]
Hi @adsingh14 yes you can work on it. You don't need to add the actual javascript action, just the button itself as this project implements CSS only buttons.

**Comment by adsingh14** [comment]
Alright ! I'm figuring the workflow of project. 
( TIP: The whole code could be shorten but it's irrelevant action for now.)

**Comment by shahednasser** [comment]
Currently we're presenting the minified version through a CDN. The reason behind that is adding the minified file in the repo caused a lot of conflicts on submitting PRs. 

If you have any other ideas on how to resolve this then submit a new issue please!

**Comment by adsingh14** [comment]
Done ! #464
