### ISSUE TITLE
[BUTTON IDEA]: Retro button

### ISSUE THREAD

**Issue by shahednasser** [shahednasser/sbuttons#431]
**1. Name of button**: Retro button

**2. Description**: A button that has a retro style to it

**3. Button Type (Animated, Special, etc...)**: Special

**4. Will you work on it?**: no

**Comment by Kazeno21** [comment]
i want to work on this. can you please assign this to me?

**Comment by shahednasser** [comment]
Hi @Kazeno21 someone is already working on this.
