### ISSUE TITLE
[BUTTON IDEA]: Share Social Buttons

### ISSUE THREAD

**Issue by shahednasser** [shahednasser/sbuttons#437]
**1. Name of button**: Share Social Buttons 

**2. Description**: Share buttons for different platforms (Facebook, twitter, etc...)

**3. Button Type (Animated, Special, etc...)**: Social

**4. Will you work on it?**: no

**Comment by iamvaishnav** [comment]
I would like to work on this.

**Comment by shahednasser** [comment]
ok @iamvaishnav I'm assigning you

**Comment by iamvaishnav** [comment]
Thanks @shahednasser

**Comment by yatharthMogra** [comment]
@shahednasser  I would like to work on it.
