### ISSUE TITLE
[BUTTON IDEA]: Follow Social Buttons

### ISSUE THREAD

**Issue by shahednasser** [shahednasser/sbuttons#438]
**1. Name of button**: Follow Social Button

**2. Description**: A social button to follow the creators social media handles

**3. Button Type (Animated, Special, etc...)**: Social

**4. Will you work on it?**: no

**submitted by**: @Archis19

**Comment by adsingh14** [comment]
Need help ?

**Comment by shahednasser** [comment]
Sure @adsingh14 I'll assign you.

**Comment by adsingh14** [comment]
How many social icons should I include ?

**Comment by shahednasser** [comment]
As much as you want. If you want you can do for the currently available ones, but make sure to include it for those that actually have the follow functionality.

**Comment by adsingh14** [comment]
I'm digging into it.

**Comment by adsingh14** [comment]
Done !  #458
