### ISSUE TITLE
Change text in Download button to "Download"

### ISSUE THREAD

**Issue by shahednasser** [shahednasser/sbuttons#44]
Currently in the [download button](https://shahednasser.github.io/sbuttons/#download_btn) section of the website, the buttons' text is "Button". Change it to "Download"

**Comment by meanmachin3** [comment]
I'll take it

**Comment by codeSalazar12** [comment]
Hey I can help it.Can u please assign it to me

**Comment by shahednasser** [comment]
Hi @meanmachin3 go ahead!

**Comment by shahednasser** [comment]
Hi @codeSalazar12 . Yes you can work on it!

**Comment by codeSalazar12** [comment]
Thanks @shahednasser

**Comment by shahednasser** [comment]
Sorry @meanmachin3 but this issue is for first-timers. Please look at other issues that require your help!

**Comment by codeSalazar12** [comment]
So it is done
![Screenshot (35)](https://user-images.githubusercontent.com/66743585/92403321-d7e3e000-f14e-11ea-8fea-f46477802a7f.png)
![Screenshot (36)](https://user-images.githubusercontent.com/66743585/92403331-de725780-f14e-11ea-951c-2a14f33584d4.png)

**Comment by shahednasser** [comment]
Great! Now please send a pull request to add your work.
If you're having trouble with doing that, please check the [contributing guide](https://github.com/shahednasser/sbuttons/blob/master/CONTRIBUTING.md)

**Comment by codeSalazar12** [comment]
Hey it is showing an error pushing the code.can u please guide me?
![Screenshot (38)](https://user-images.githubusercontent.com/66743585/92403813-e252a980-f14f-11ea-8ca6-49dea03771ae.png)

**Comment by codeSalazar12** [comment]
okay it is solved.I am making a pull request

**Comment by codeSalazar12** [comment]
Hey can u please help me i am not able to push the code and pull the request

**Comment by shahednasser** [comment]
What is the problem exactly?

**Comment by codeSalazar12** [comment]
I think i solved it i already made a pull request check it

**Comment by shahednasser** [comment]
Resolved by #47
