### ISSUE TITLE
Add action to comment on PR after deploying it

### ISSUE THREAD

**Issue by shahednasser** [shahednasser/sbuttons#444]
We have an action called [Surge PR Preview](https://github.com/marketplace/actions/surge-pr-preview) that previews a PR on a surge website. This is very helpful as it makes it easier to see the changes of the PR.

Currently, the action does not leave a comment with the URL of the deployed PR, it just deploys it but it appears in the action log. This is apparently not possible due to github limitation on adding a comment from an action on a PR.

I'm not sure if it's possible but I would like to add an action that submits a comment on the PR after the Surge PR Preview action succeeds with the URL of the deployed PR. This will make it easier for me and the contributors as well to see their changes.

If it's not possible with this action and you know of a better action to do this please let me know as well. (It doesn't have to be surge but it's the easiest).

**Comment by HeinKhantZaw** [comment]
Can I work for this issue?

**Comment by shahednasser** [comment]
Sure @HeinKhantZaw. Let me know how you want to do it.

**Comment by HeinKhantZaw** [comment]
Hi @shahednasser . I don't know if it's going to work or not but I am thinking about using Nelify deploy action. How about that?

**Comment by HeinKhantZaw** [comment]
![image](https://user-images.githubusercontent.com/40730345/94842146-0c427780-0441-11eb-9d24-74d2572b5219.png)

Here is the action for comment to PR I've tested in my repo. It's used by netlify deploy action.

**Comment by shahednasser** [comment]
Is netlify free? Also we need to confirm that it works on forked repositories so we will need to test it. I'll let you know with more details in a bit.

**Comment by HeinKhantZaw** [comment]
Yes. It is free for personal projects. I don't know exactly if it works for forked repos but you can check more here.
[https://docs.netlify.com/#get-started](url)

**Comment by HeinKhantZaw** [comment]
I will submit pull request for preview.yml update if everything is ok. Please let me know again.

**Comment by shahednasser** [comment]
I have created a new branch called preview-action. Please submit a new PR to merge the changes to it so we can test it on that branch.

**Comment by shahednasser** [comment]
Are there any keys I'm required to add to this repo? Please let me know as well.

**Comment by HeinKhantZaw** [comment]
You need to add NETLIFY_AUTH_TOKEN and NETLIFY_SITE_ID.
For NETLIFY_AUTH_TOKEN, you can get it from here [personal access token](https://app.netlify.com/user/applications#personal-access-tokens)
For NETLIFY_SITE_ID, you need to add API ID of [your Netlify site](https://app.netlify.com/start)
