### ISSUE TITLE
[BUTTON IDEA]:

### ISSUE THREAD

**Issue by awantika10** [shahednasser/sbuttons#454]
**1. Name of button**:  Raised Button

**2. Description**: Raised Button typically rectangular button that lifts (the shading indicates that it is possible to click). Raised buttons add dimension to mostly flat layouts. They emphasize functions on busy or wide spaces.

**3. Button Type (Animated, Special, etc...)**:Raised buttons lift and fill with color on press.

**4. Will you work on it?**:
Using CSS shadows and animations

**Comment by shahednasser** [comment]
Hi @awantika10 is this different than the currently present "Click button?"

**Comment by awantika10** [comment]
It's the same just the styling changes

**Comment by awantika10** [comment]
There are plenty of buttons according to UI. It's just a type of button which differs in styling

**Comment by awantika10** [comment]
This is done I guess
