### ISSUE TITLE
[BUTTON IDEA]: BUFFER BUTTON

### ISSUE THREAD

**Issue by awantika10** [shahednasser/sbuttons#457]
**1. Name of button**: Submit Button

**2. Description**: As soon as you press the submit button, you'll get animated tick mark

**3. Button Type (Animated, Special, etc...)**:Animated 

**4. Will you work on it?**: Yes
![IMG_20201001_192458](https://user-images.githubusercontent.com/71998138/94818793-2158df80-041c-11eb-99dd-32aa859143e6.jpg)
![IMG_20201001_192513](https://user-images.githubusercontent.com/71998138/94818876-36ce0980-041c-11eb-9bf2-4c136361997d.jpg)
![IMG_20201001_192527](https://user-images.githubusercontent.com/71998138/94818907-43eaf880-041c-11eb-84c7-bed2a638ebc0.jpg)

**Comment by Deepakmukka1** [comment]
@awantika10 i can do this can you assign it to me?

**Comment by shahednasser** [comment]
Hi @awantika10 thank you for your idea, but we're making this project without any javascript, only CSS.
