### ISSUE TITLE
Add message on clicking class names

### ISSUE THREAD

**Issue by shahednasser** [shahednasser/sbuttons#48]
When clicking on class names below a button it will be copied to the clipboard. Add a success message that indicates that the classes are copied. You can use something like bootstrap's [Toasts](https://getbootstrap.com/docs/4.3/components/toasts/) or maybe just a [tooltip](https://getbootstrap.com/docs/4.3/components/tooltips/) over the element saying "Copied!"

**Comment by Hrishi-Raj** [comment]
@shahednasser May I work on this Issue?

**Comment by shahednasser** [comment]
Sure go ahead

**Comment by shahednasser** [comment]
Resolved by #56
