### ISSUE TITLE
Move CSS rules for "getStarted.html" from index.css to a new file

### ISSUE THREAD

**Issue by shahednasser** [shahednasser/sbuttons#485]
CSS rules exclusive to getStarted.html are currently also in index.css. We need to move them to a new file (preferably of the same name) then import that file in getStarted.html

**Comment by baspalinckx** [comment]
This looks like a great first issue! Can I try?

**Comment by shahednasser** [comment]
sure @baspalinckx I'll assign you.

**Comment by aryan040501** [comment]
Hi, Can I try this?

**Comment by baspalinckx** [comment]
That should do it: https://github.com/shahednasser/sbuttons/pull/491
