### ISSUE TITLE
Add Copy to Clipboard button for code in How to Use section

### ISSUE THREAD

**Issue by shahednasser** [shahednasser/sbuttons#49]
Add Copy to Clipboard button for the code blocks in How to Use section. These blocks use [Prism.js](https://prismjs.com/), so maybe you need to check solutions on the plugin's page first, but if you have another solution that's fine too.

**Comment by Yashi-Chawla** [comment]
Hi, can I work on this?

**Comment by shahednasser** [comment]
Yes go ahead!

**Comment by shahednasser** [comment]
Resolved by #64
