### ISSUE TITLE
Change Scroll to Top speed (Mobile devices bug)

### ISSUE THREAD

**Issue by shahednasser** [shahednasser/sbuttons#50]
On mobile devices, scroll-to-top is too quick. Change the speed to something slower but make sure it's not too slow.
You can change the speed in `assets/js/index.js`

**Comment by Develrockment** [comment]
I would like to implement this as my first issue

**Comment by shahednasser** [comment]
Great, go ahead!

**Comment by shahednasser** [comment]
Resolved by #53
