### ISSUE TITLE
Help in testing Netlify deployment

### ISSUE THREAD

**Issue by shahednasser** [shahednasser/sbuttons#515]
I need someone free to help test draft Netlify deployment with me. Please comment below if you can work on it with me.

The testing will just be you creating pull requests when needed.

**Comment by HADES-01** [comment]
@shahednasser I would love to help you out.

**Comment by shahednasser** [comment]
Ok great @HADES-01 . Please create a pull request with any change in index.html. The change is not important so it can be anything
