### ISSUE TITLE
[BUTTON IDEA]:Button with Sound

### ISSUE THREAD

**Issue by palakyadav1807** [shahednasser/sbuttons#516]
**1. Name of button**: Button with sound

**2. Description**: Produces a confirmation sound on clicking

**3. Button Type (Animated, Special, etc...)**:simple

**4. Will you work on it?**:yes

**Comment by shahednasser** [comment]
Hi @palakyadav1807 thank you for your idea but we need to implement the buttons with CSS only, so this idea can not be implemented.

**Comment by palakyadav1807** [comment]
Really sorry , i am new to open source
