### ISSUE TITLE
Fix typo in CONTRIBUTING.md

### ISSUE THREAD

**Issue by shahednasser** [shahednasser/sbuttons#523]
There's a typo in CONTRIBUTING.md in [Instructions](https://github.com/shahednasser/sbuttons/blob/master/CONTRIBUTING.md#instructions) item 3 in the code block ("to make changes to the website..."). The typo is inside the code block in the comments. the typo is "normat" should be changed to normal.

**Comment by Graviton5** [comment]
I would like to work on this.

**Comment by shahednasser** [comment]
Hi @Graviton5 this as the "first-timers-only" label to encourage beginner new comers to work on it. As you are a contributor now, you can't work on it.

**Comment by APalpattuwar7** [comment]
Can I take this? This would be my first contribution.

**Comment by shahednasser** [comment]
Yes @APalpattuwar7 you may go ahead

**Comment by ShivaniThevar** [comment]
Is there any other changes to be done... as I can see someone already fixed the typo error...?

**Comment by shahednasser** [comment]
No @ShivaniThevar this issue has been resolved
