### ISSUE TITLE
Add hr under Disabled Buttons in Get Started page

### ISSUE THREAD

**Issue by shahednasser** [shahednasser/sbuttons#528]
an `<hr>` element is missing under Disabled Buttons in Get Started page. Should be similar to other titles in the page.

**Comment by JakubIwanowski** [comment]
Can I work on this issue?

**Comment by Ishaan0905** [comment]
Can I work on this issue? I got revert on the Normat issue

**Comment by shahednasser** [comment]
Sure @JakubIwanowski I'll assign you.

**Comment by faraz16iqbal** [comment]
Hey is this issue still open?

**Comment by shahednasser** [comment]
@faraz16iqbal this issue has been resolved
