### ISSUE TITLE
[BUTTON IDEA]:minus button

### ISSUE THREAD

**Issue by gokul112** [shahednasser/sbuttons#536]
**1. Name of button**: Minus button

**2. Description**: Minus button to reduce/remove the number of items added in cart

**3. Button Type (Animated, Special, etc...)**:Icon

**4. Will you work on it?**:I will work on it!

**Comment by shahednasser** [comment]
Hi @gokul112 it's a good idea but it's similar to the plus sign, the person would just change the icon. I'm not sure whether that is necessary or not.

**Comment by gokul112** [comment]
Hi @shahednasser yeah, you're right. But in this case, they can't readily use the components available they have to edit the CSS and then they have to make it available
can I know your thoughts?

**Comment by shahednasser** [comment]
That makes sense. Maybe we should work on it from a different perspective. I'll create a new issue of creating a base icon button to be used and then the user can just set the content of the icon. If we add a button for every icon out there then it will be endless.

Let me know if you would like to work on it.

**Comment by gokul112** [comment]
yeah i will work on it !
