### ISSUE TITLE
Modify How to Use section's text

### ISSUE THREAD

**Issue by shahednasser** [shahednasser/sbuttons#57]
Make the following changes to the section:

1. Change "The CSS file is available for download here.
Download the file and link it as a stylesheet in between your <head> tags, as shown below." to "You can download the CSS file here and then add it to your html file inbetween the <head> tags:" make sure the "here" points to the URL to download the CSS file.
2. Change "You can copy the sentence above, and replace the "/path/to/sbuttons.min.css" with the proper path to where you have the file stored." with "Make sure to replace  "/path/to/sbuttons.min.css" you stored it in"
3. Change "Additionally, you can also use the buttons by using the CDN. You can directly copy the line below and place it inside your <head> tags, just like you would if you were to download the file." to" Or instead of downloading the file, you can use the CDN:"

**Comment by ashleypean** [comment]
Can I grab this?

**Comment by shahednasser** [comment]
of course!

**Comment by ashleypean** [comment]
For request #2, would you like the text to state: 
"Make sure to replace "/path/to/sbuttons.min.css" you stored it in" 
**or** 
"Make sure to replace "/path/to/sbuttons.min.css" with the path you stored it in" ?

**Comment by shahednasser** [comment]
The latter sounds better

**Comment by shahednasser** [comment]
Resolved by #70
