### ISSUE TITLE
Remove box shadow for click buttons

### ISSUE THREAD

**Issue by shahednasser** [shahednasser/sbuttons#69]
Currently, on click adds a box shadow to all button types. We need to remove this only for Animated Click buttons, as it changes the design of the button.

try adding something like `box-shadow: none !important;` for click buttons when it's `:active` or any good solution.  
Make sure to read the [contribution guide](https://github.com/shahednasser/sbuttons/blob/master/CONTRIBUTING.md) to learn how you can make changes properly.

**Comment by isonnymichael** [comment]
Can I work on it ?

**Comment by shahednasser** [comment]
@isonnymichael  Someone started working on it in #75
