### ISSUE TITLE
Add hamburger side menu on mobile devices

### ISSUE THREAD

**Issue by shahednasser** [shahednasser/sbuttons#7]
Add a menu icon that only appears on mobile devices (less than 768px of width) and add the appropriate css or js to make the menu icon toggle the existing sidebar menu.
As bootstrap is used in this website, you can also use bootstrap to do this functionality.
Font awesome is also used on the website so you can use it for the hamburger menu icon.

**Comment by valeriaoshiro** [comment]
Hi, can I work on this?

**Comment by shahednasser** [comment]
@valeriaoshiro yes please!

**Comment by hrithiksh101** [comment]
Is your issue resolved ? 
i can also help if you need

**Comment by shahednasser** [comment]
@hrithiksh101 there's currently a PR but it's not resolved yet. You can try if you want.

**Comment by hrithiksh101** [comment]
I have made some commits to this project , are they done , sorry for asking but i'm first time user of github .

**Comment by hrithiksh101** [comment]
i have also added hamburger menu for the mobile screens , i don't know if i'm late but my commits can be seen in the pull requests section . i don't know if the commits are successfully pushed . 
can you confirm ? 😃

**Comment by shahednasser** [comment]
Resolved by #58
