### ISSUE TITLE
Disable selection of logo text

### ISSUE THREAD

**Issue by shahednasser** [shahednasser/sbuttons#71]
Add a rule to `.logo h1` to disable user selection. Make sure to add the changes to `assets/css/index.css`.  Check out the screenshot for an example
![sButtons-Simple-and-Creative-Buttons](https://user-images.githubusercontent.com/27354907/92785571-3360d880-f3b0-11ea-8710-2162675fa06d.png)

**Comment by shubhampandeyhld** [comment]
can you elaborate this issue ?

**Comment by shahednasser** [comment]
Hi @shubhampandeyhld I updated my post to clarify what I mean, however this issue is for first timers only so, please look at other issues that don't have the first-timers-only label if you wanna help!

**Comment by shubhampandeyhld** [comment]
> 
> 
> Hi @shubhampandeyhld I updated my post to clarify what I mean, however this issue is for first timers only so, please look at other issues that don't have the first-timers-only label if you wanna help!

ok

**Comment by CodeMode1** [comment]
Hi @shahednasser 
Can I take this issue ?

Thanks !

**Comment by shahednasser** [comment]
Hi @CodeMode1 go ahead!

**Comment by CodeMode1** [comment]
Hi @shahednasser ,
I have submitted the PR https://github.com/shahednasser/sbuttons/pull/111#issue-486211848

Cheers !
