### ISSUE TITLE
Add tagline under logo

### ISSUE THREAD

**Issue by shahednasser** [shahednasser/sbuttons#8]
Add a tagline under the logo that says "Made with ❤︎". Either use a sans-serif font (not the current font being used for the logo) or find something on Google Fonts.

Any style additions you make, please add them in `assets\css\index.css`. If you add a Google Font, add it at the end of the `<head>` tag.

**Comment by valeriaoshiro** [comment]
Hello, I would like to work on this. Thank you

**Comment by shahednasser** [comment]
Hi @valeriaoshiro , someone already is working on this issue. Please try other issues, I would love your help on them!

**Comment by shahednasser** [comment]
Currently, no one is working on this issue if someone wants to work on it.
