### ISSUE TITLE
Remove outline for hamburger menu & close buttons

### ISSUE THREAD

**Issue by shahednasser** [shahednasser/sbuttons#80]
On focus for `.sidebar-toggler` and `.close-sidebar`, an outline is shown. We need to remove it.  
Changes should be made in `assets/css/index.css`

**Comment by Annysah** [comment]
Hello @shahednasser,
I would love to work on this!

**Comment by shahednasser** [comment]
Hi @Annysah . This issue is meant for first timers (beginners). If you would like to help with other issues that don't have the "first-timers-only" label then please go ahead!

**Comment by chelsi-001011** [comment]
Hi @shahednasser ! Can I work on this issue?

**Comment by shahednasser** [comment]
Yes go ahead!

**Comment by chelsi-001011** [comment]
I have made a pull request with the changes. commit id - fb79558
