### ISSUE TITLE
Add overlay when sidebar opens on small devices

### ISSUE THREAD

**Issue by shahednasser** [shahednasser/sbuttons#83]
When the sidebar opens on small devices, add an overlay that darkens a little the rest of the page.

**Comment by shubhampandeyhld** [comment]
Please assign me this issue also.

**Comment by shahednasser** [comment]
ok I assigned you

**Comment by shahednasser** [comment]
Hello @shubhampandeyhld is there any update on this?

**Comment by shubhampandeyhld** [comment]
Sorry I am bit busy these days.
No I can't update .

**Comment by shahednasser** [comment]
I understand it's not a problem. If by the end of this weekend you still find it hard to work on these issues let me know so maybe we can give them to someone else.

**Comment by shahednasser** [comment]
Unassigning to give others a chance

**Comment by JLambertazzo** [comment]
Hey, I'd like to work on this! @shahednasser

**Comment by shahednasser** [comment]
Hi @JLambertazzo go ahead!
