### ISSUE TITLE
Remove extra padding/margin for sidebar-toggler

### ISSUE THREAD

**Issue by shahednasser** [shahednasser/sbuttons#84]
On small devices, there's an extra padding/margin to the left of `.sidebar-toggler` we need it removed.

**Comment by hauchongtang** [comment]
I would like to work on this.

**Comment by shahednasser** [comment]
Thank you for contributing @hauchongtang but this issue is meant for first timers only and as it says in the contribution guide, issues with the label first-timers-only are for beginners. If you wanna contribute please checkout other issues that don't have the first-timers-only label. Thank you!

**Comment by caseycling** [comment]
Can I work on this issue?

**Comment by shahednasser** [comment]
sure!
