### ISSUE TITLE
Close sidebar on clicking outside of it

### ISSUE THREAD

**Issue by shahednasser** [shahednasser/sbuttons#85]
Currently, only clicking the close button closes the sidebar. Add a click event that closes the sidebar by clicking outside of it.

**Comment by Pratyush-Saxena** [comment]
I would like to take this up @shahednasser

**Comment by shahednasser** [comment]
Sure!

**Comment by Pratyush-Saxena** [comment]
@shahednasser ...can you pls tell the condition that checks ..whether the sidebar is open or not

**Comment by shahednasser** [comment]
the sidebar should have class `.animate__slideInLeft` and not have the class `.hide-sidebar` when it is opened

**Comment by Pratyush-Saxena** [comment]
> .animate__slideInLeft

it isn't working...i am trying something like this ->
```
$(window).on("click",function (event) {
    event.stopPropagation();
    let sidebar = $(".sidebar");
    if(event.target!=sidebar && sidebar[0].classList.contains(".animate__slideInLeft") && (!sidebar[0].classList.contains(".hide-sidebar"))){
      sidebar.addClass("animate__slideOutLeft");
    window.setTimeout(function () {
      sidebar.toggleClass("hide-sidebar");
      sidebar.removeClass("animate__slideOutLeft");
    }, 1000);
    }
  }); 
```

**Comment by shahednasser** [comment]
You can't assign `$(".sidebar")` to `sidebar` and then use it as a JS DOM element in the following code. Please use jquery functions (for example, instead of `sidebar[0].classList.contains(".animate__slideInLeft")` use `sidebar.hasClass("animate__slideInLeft")`

**Comment by Pratyush-Saxena** [comment]
> You can't assign `$(".sidebar")` to `sidebar` and then use it as a JS DOM element in the following code. Please use jquery functions (for example, instead of `sidebar[0].classList.contains(".animate__slideInLeft")` use `sidebar.hasClass("animate__slideInLeft")`

that too isn't  working

**Comment by shahednasser** [comment]
In your code, it also says `$(window).on('click')...` try changing `window` to `"body"`
