### ISSUE TITLE
Overflowing items in sidebar not showing on small devices

### ISSUE THREAD

**Issue by shahednasser** [shahednasser/sbuttons#86]
Sidebar on small devices does not allow scrolling at the moment. Add `overflow-y: auto` to allow scroll. Also, Make the scroll bar look nice (not the usual scroll bar)

**Comment by shubhampandeyhld** [comment]
can I work on it ?

**Comment by shahednasser** [comment]
Yes go ahead

**Comment by mayankmohak** [comment]
can i do it?

**Comment by shahednasser** [comment]
Someone is already assigned to this issue. Please find an issue that isn't assigned to anyone.

**Comment by shahednasser** [comment]
Hello @shubhampandeyhld any update on this? as you can see this issue has a high priority

**Comment by shahednasser** [comment]
Unassigning to give others a chance to work on this.

**Comment by isonnymichael** [comment]
Hi @shahednasser , can i work on this ? I will try fix this quickly
