### ISSUE TITLE
Remove clipboard button outline on :focus

### ISSUE THREAD

**Issue by shahednasser** [shahednasser/sbuttons#92]
For button of class `.clipboard`, set `outline: 0;` on `:focus`

**Comment by gathoni-k** [comment]
Can I work on this?

**Comment by shahednasser** [comment]
sorry this is for first timers only! (read more in the [contributing guidelines](https://github.com/shahednasser/sbuttons/blob/master/CONTRIBUTING.md)). If you would like to contribute to this repo please find issues without the first-timers-only label.

**Comment by gathoni-k** [comment]
Alright, thank you!

**Comment by dhruv-doshi** [comment]
Hey @shahednasser 
I am would like to work on this issue.

**Comment by shahednasser** [comment]
sure!
