### ISSUE TITLE
Close sidebar on clicking on link in small devices

### ISSUE THREAD

**Issue by shahednasser** [shahednasser/sbuttons#95]
When clicking a link on small devices and the sidebar is opened, it should close automatically.

**Comment by caseycling** [comment]
Can I be assigned for this issue?

**Comment by caseycling** [comment]
I think I have solved the issue. Let me know if it's okay for me to push the code for review

**Comment by shahednasser** [comment]
Please create a pull request for me to review it

**Comment by caseycling** [comment]
Nevermind, I didn't solve it yet. Could I email you a question I have about the code?

**Comment by shahednasser** [comment]
Yes sure

**Comment by caseycling** [comment]
Actually I can just do a pull review and ask my question in there so you can better see the code.

**Comment by caseycling** [comment]
Awesome, fixed the issue and pushed it to my branch. However I can't seem to find the pull request?
