### ISSUE TITLE
Add light/dark mode

### ISSUE THREAD

**Issue by shahednasser** [shahednasser/sbuttons#97]
Add a toolbar that switches between light and dark mode. The toolbar can be placed in any place as long as it doesn't interfere with the content of the website.

Light mode should be the default, which is what the website looks like now. Dark mode should just change the background to a dark color and change sidebar menu links or header links to a light color. Don't make any changes to the buttons for now.

When creating the toolbar, try to make it something simple. I think it would be best if you can use icons to signify Light and Dark modes. We are already using font awesome on the website, so maybe use a "sun" icon for light, and "moon" icon for dark.

**Comment by cosay** [comment]
@shahednasser I would like to work on it

**Comment by shahednasser** [comment]
Great go ahead!
