### ISSUE TITLE
Assign correct labels based on issue

### ISSUE THREAD

**Issue by shahednasser** [shahednasser/sbuttons#98]
I want to add labels to issues to differentiate between issues directed towards website and those towards buttons. Please do not start working on this issue before commenting about it, as it can cause a mess. After commenting on her and getting approval, you can go ahead and work on it. Once you're done, leave a comment saying so.  
Make sure to read the README and contribution guide before working on this to get an idea of where each issue belongs.

**Comment by caseycling** [comment]
Can I be assigned this issue?

**Comment by shahednasser** [comment]
Yes go ahead! Please read the contribution guide, take a look at the website and get some understanding of which issues would refer to working on the buttons and which would refer to working on the website before you start. Let me know here when you're done.

**Comment by shahednasser** [comment]
Hello @caseycling , is there any feedback on this? please let me know if you're having any trouble.

**Comment by shahednasser** [comment]
This issue is now unassigned to give other people a chance to work on it.
