### ISSUE TITLE
Sort buttons alphabetically

### ISSUE THREAD

**Issue by shahednasser** [shahednasser/sbuttons#99]
Currently, the list of buttons that are appearing on the website are in `assets/js/buttons-examples.js` in the variable `buttons`. We need this list sorted alphabetically, with the exception of "Basic Buttons" as it should be the first.
For example, now the list is "Basic Buttons", "Outline Buttons", "Hover Buttons", "Animated Buttons", etc.. It should become "Basic Buttons", "Animated Buttons", etc...  
Also, sort the child types in each type (children of animated buttons or icon buttons)

**Comment by mayankmohak** [comment]
I would like to work on it.
Doubt: Shall i write a sorting algo for it or do it manually.

**Comment by shahednasser** [comment]
Please do it manually, we don't want to waste execution time on it.

**Comment by mayankmohak** [comment]
On it.

**Comment by mayankmohak** [comment]
made a pull req.
